# Generated by Django 3.0.3 on 2020-06-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetOffer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='nowa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='ingredients',
            field=models.ManyToManyField(to='SweetOffer.Ingredient'),
        ),
    ]
