# Generated by Django 3.0.3 on 2020-06-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SweetOffer', '0003_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweetOffer.Offer')),
            ],
        ),
    ]
