# Generated by Django 3.0.3 on 2020-06-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SweetOffer', '0005_auto_20200603_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='IngredientOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweetOffer.Ingredient')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SweetOffer.Offer')),
            ],
        ),
    ]
