# Generated by Django 3.0.3 on 2020-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetOffer', '0008_auto_20200610_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_link',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
