# Generated by Django 3.0.3 on 2020-06-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetOffer', '0009_auto_20200611_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_text',
        ),
        migrations.AlterField(
            model_name='description',
            name='description_text',
            field=models.CharField(max_length=300),
        ),
    ]
