# Generated by Django 3.0.3 on 2020-06-18 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SweetOffer', '0011_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='type_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SweetOffer.Type'),
            preserve_default=False,
        ),
    ]
