# Generated by Django 3.0.3 on 2020-06-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SweetOffer', '0012_offer_type_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
    ]
