# Generated by Django 3.0.3 on 2020-07-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SweetOffer', '0013_auto_20200623_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
